### ISSUE TITLE
Missing FhirCareTeamExtension and FhirOrganizationExtension from v0.0.2-SNAPSHOT release

### ISSUE THREAD

**Issue by FikriMilano** [opensrp/fhir-common-utils#5]
These classes are needed in the Practitioner Details refactor PR https://github.com/opensrp/fhircore/pull/1520

Try to download the zip release for verification https://github.com/opensrp/fhir-common-utils/releases/tag/v0.0.2-SNAPSHOT

<img width="1212" alt="Screen Shot 2022-08-12 at 16 16 39" src="https://user-images.githubusercontent.com/62053304/184324323-d3c9e415-f0ee-45fa-ba63-4164b0ff9e75.png">

@dubdabasoduba @rehammuzzamil

**Comment by FikriMilano** [comment]
@rehammuzzamil could you investigate?

**Comment by dubdabasoduba** [comment]
@FikriMilano I don't this is needed we refactored the code to return actual FHIR resources. This was done because the SDK could not save custom FHIR resources. 

@rehammuzzamil Am i right?

**Comment by FikriMilano** [comment]
@dubdabasoduba 
Actually we still need those for parsing the JSON payload.

Since it's custom classes, we have to register those classes to the fhirParser.
Otherwise it will throw an error of unknown resource.

That's the issue I'm facing.

**Comment by dubdabasoduba** [comment]
What do you mean they are custom classes? Are they an extension of the FHIR Organization & CareTeam class?  @rehammuzzamil ?

**Comment by FikriMilano** [comment]
> What do you mean they are custom classes? Are they an extension of the FHIR Organization & CareTeam class?  @rehammuzzamil ? 

Yeah, those 2 extension for Organization and CareTeam.

**Comment by dubdabasoduba** [comment]
> > What do you mean they are custom classes? Are they an extension of the FHIR Organization & CareTeam class?  @rehammuzzamil ?
> 
> Yeah, those 2 extension for Organization and CareTeam.

Mmh, interesting. I thought we had discussed removing that. Let me see what @rehammuzzamil says. Maybe I am missign something

**Comment by rehammuzzamil** [comment]
> > > What do you mean they are custom classes? Are they an extension of the FHIR Organization & CareTeam class?  @rehammuzzamil ?
> > 
> > 
> > Yeah, those 2 extension for Organization and CareTeam.
> 
> Mmh, interesting. I thought we had discussed removing that. Let me see what @rehammuzzamil says. Maybe I am missign something

Yes @dubdabasoduba , this is correct. We have removed these classes as extensions were not really needed and we can directly a list of Fhir Resources i.e. care teams and organizations.

**Comment by rehammuzzamil** [comment]
@FikriMilano Could you please let me know the use-case why these classes are needed?
As we have modified the codebase earlier to use Fhir resources in the response and the idea was to define least custom classes.
![pracctdetails](https://user-images.githubusercontent.com/62061579/184345257-782294d6-d99b-4cf8-a1d6-9413dd4fbc4c.png)

As you can see over here `FhirPractitionerDetails` does not use FhirCareTeamExtension and FhirOrganizationExtension anymore, we have replaced it to use careteams and organizations objects instead.

Please let me know if there is anything missing.
cc: @dubdabasoduba

**Comment by FikriMilano** [comment]
Hmm I see, yeah that's interesting, that shouldn't be a problem then.
I was getting the error of missing FhirCareTeamExtension.

Let me do some more debugging and get back at you.

**Comment by FikriMilano** [comment]
Okay, I no longer see the error on my end, I made a bit of change in the parser.

Anyways, we are now able to parse the full payload into the app.

Thanks @rehammuzzamil @dubdabasoduba
